server.port=8080
spring.application.name=gemini-app
spring.ai.vertex.ai.gemini.project-id=collab-verse-466620
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.3
spring.ai.vertex.ai.gemini.chat.options.top-k=32
spring.ai.vertex.ai.gemini.chat.options.top-p=0.9
spring.ai.vertex.ai.gemini.chat.options.max-output-tokens=1024
spring.graphql.graphiql.enabled=true