server.port=8080
spring.application.name=gemini-app

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- GEMINI CHAT CONFIG ---
spring.ai.vertex.ai.gemini.project-id=
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.3
spring.ai.vertex.ai.gemini.chat.options.top-k=32
spring.ai.vertex.ai.gemini.chat.options.top-p=0.9
spring.ai.vertex.ai.gemini.chat.options.max-output-tokens=1024

# --- VERTEX AI EMBEDDING CONFIG ---
spring.ai.vertex.ai.embedding.project-id=${spring.ai.vertex.ai.gemini.project-id}
spring.ai.vertex.ai.embedding.location=${spring.ai.vertex.ai.gemini.location}
spring.ai.vertex.ai.embedding.text.options.model=text-embedding-004

# --- DOCUMENT AI CONFIG ---
gcp.document-ai.location=us
gcp.document-ai.api-endpoint=us-documentai.googleapis.com:443
gcp.processor-id=
aws.s3.bucket-name=vertex-spring-ai-local-stack-s3-document-store
aws.sqs.queue-name=vertex-spring-ai-local-stack-sqs-queue
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.max-document-batch-size=1000
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=false
spring.ai.vectorstore.pgvector.dimensions=768
# --- PROMPT CONFIG ---
app.prompt.system.prompt=classpath:/prompts/systemPrompt.st

# Docker PGVector/Postgres is exposed by localstack/docker-compose.yaml as 127.0.0.1:5432->5432.
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/vertex_spring_ai_embeddings
spring.datasource.username=postgres
spring.datasource.password=password

spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

springdoc.swagger-ui.path=/swagger-ui.html
spring.graphql.graphiql.enabled=true
spring.docker.compose.file=./localstack/docker-compose.yaml

management.endpoints.web.exposure.include=health,info,refresh,flyway
# Enable Flyway Output and Debug Logs
logging.level.org.flywaydb.core=DEBUG
# Enable debug logging for Google Cloud libraries
logging.level.com.google.cloud=DEBUG
logging.level.com.google.api=DEBUG
# Specifically for gRPC (used by Document AI)
logging.level.io.grpc=DEBUG
# If you are using the REST client instead of gRPC
logging.level.com.google.api.client.http=DEBUG